### ISSUE TITLE
Android 10+

### ISSUE THREAD

**Issue by vickodin** [1isten/WhoIsThat#1]
Hi!
I think something has changed in new Android releases.

I tested on Android 10 and I've got null value. Maybe need new permissions or something else, I don't know.

May I ask you a question? Is it possible to make fix for work it on the latest Android devices also?

Thanks in advance!

**Comment by 1isten** [comment]
Hi @vickodin I just [updated the code](https://github.com/1isten/WhoIsThat/commit/d4a1ecafd04f323485742b97c6d7311a64e93e86) and tested on my Android 10 (Oneplus 7T). It should be ok now :D

You can try the latest release apk: https://github.com/1isten/WhoIsThat/releases/tag/v1.3

**Comment by vickodin** [comment]
@1isten Thank you. It works now!
